### ISSUE TITLE
The page "From HTML to HTML" could get a small update

### ISSUE THREAD

**Issue by RiZKiT** [thymeleaf/thymeleaf.github.com#13]
The part [Can I use HTML5 already?](http://www.thymeleaf.org/doc/fromhtmltohtmlviahtml.html#can-i-use-html5-already) seems to be dated in 2011 and could get a small update.

Second, the link to the Thymeleaf team in the footer is invalid by now.

**Comment by ultraq** [comment]
The section did get a small 2016 update with the website redesign, but it was lacking the links discussed here.  Added to be included with the next time the docs get generated.
