### ISSUE TITLE
Bad layout of Tutorial pages on mobile screen

### ISSUE THREAD

**Issue by coffee4dev** [thymeleaf/thymeleaf.github.com#16]
Right area (content) gets shifted to the left, under the left summary menu, leaving a gap on the right side. Would appreciate if it could be corrected so.e way.

**Comment by danielfernandez** [comment]
@ultraq can you have a look at this?

**Comment by coffee4dev** [comment]
By the way, I'm on Nexus 5

**Comment by ultraq** [comment]
Sure sure :)

**Comment by ultraq** [comment]
Ah, the tutorials.  Yeah, I never went down to a mobile form factor when testing them, so never came up with a good mobile design.  I'll try to come up with something, maybe have the left-hand-side collapse to a button menu to make way for the content.

**Comment by coffee4dev** [comment]
That'd be great, thanks for the speedy reply!

**Comment by ultraq** [comment]
@danielfernandez, I've updated the docs project, taking a mobile-first approach to the responsive design of the tutorial pages (https://github.com/thymeleaf/thymeleaf-docs/commit/8158a26ad0ee513fe94e8215e62dc44c6f897621).  This makes for a nicer viewing experience for those using smaller screens like mobile devices.  I've started with hiding the table-of-contents behind a floating Thymeleaf icon that, when clicked, brings up the table-of-contents.  (Clicking it again hides the contents, clicking a link in the contents navigates to the section and hides the contents).

Tested on Firefox on my Galaxy S3 (so down to a width of 360 pixels), although I tried the responsive design view on Firefox desktop down to old iPhone size (width of 320 pixels).  Did we have a CI for pushing out doc changes now, or is it still mostly manual? (ie: push commits to this repo)

**Comment by danielfernandez** [comment]
@ultraq if you push the changes to github, I can publish it from the releases machine on Amazon, which is the one having the right configuration for creating the right PDF and MOBI output too. Unfortunately some maven configuration issues prevent me from giving you access to that machine yet :-( so I'll have to do it myself for now.

This said, in this case you have not modified anything for PDF or MOBI, so if you want to generate the `.html` docs yourself locally and just push those to `thymeleaf.github.com`, that would be perfectly fine... it's still a manual process. Generate on `thymeleaf-docs`, copy to `thymeleaf.github.com`, push.

**Comment by ultraq** [comment]
OK, manual process time.

**Comment by ultraq** [comment]
@coffee4dev, changes are now live.  Browsing through the tutorial docs on the Thymeleaf website should be much nicer on your Nexus 5 :)

**Comment by coffee4dev** [comment]
@ultraq indeed, it's usable now. Thank you, that was super fast!
