### ISSUE TITLE
Missing info about WHITESPACE separator for ${#numbers}

### ISSUE THREAD

**Issue by dstr47** [thymeleaf/thymeleaf.github.com#17]
There is a following comment in "Tutorial: Using Thymeleaf" -> Appendix B (http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#numbers):

/* 
 * Set minimum integer digits and thousands separator: 
 * 'POINT', 'COMMA', 'NONE' or 'DEFAULT' (by locale).
 * Also works with arrays, lists or sets
 */

No WHITESPACE modifier is listed in this comment (added here: https://github.com/thymeleaf/thymeleaf/issues/6).

**Comment by ultraq** [comment]
Thanks for letting us know about this!  I've updated the source from which our online docs are generated (you can see the linked commits in this issue) and will regenerate/upload those changes soon.
