### ISSUE TITLE
Javadoc needs an update to match with the published code?

### ISSUE THREAD

**Issue by JurrianFahner** [thymeleaf/thymeleaf.github.com#18]
In the javadoc about [TemplateEngine](http://www.thymeleaf.org/apidocs/thymeleaf/2.1.4.RELEASE/org/thymeleaf/TemplateEngine.html) the following code snippets are published:

``` java
final IContext ctx = new Context();
ctx.setVariable("allItems", items);
```

and

```
final IContext ctx = new WebContext(request, servletContext);
ctx.setVariable("allItems", items); 
```

The problem with this code is that the interface `IContext` doesn't have the the `setVariable` and `setVariables` methods in version 2.1.4.RELEASE. 

The workaround is to apply (by not programming to an interface): 

``` java
final Context ctx = new Context();
ctx.setVariable("allItems", items);
```

So it is not a great problem, anyway...

**Comment by ultraq** [comment]
Looks like it was still a problem in the 3.0 branch too.  Fixed to appear in the next patch for the 3.0 and 2.1 branches of Thymeleaf.
