### ISSUE TITLE
Link 404s in Using Thymeleaf tutorial

### ISSUE THREAD

**Issue by RobinStephenson** [thymeleaf/thymeleaf.github.com#22]
[thymeleaf.github.com/doc/tutorials/2.1/usingthymeleaf.html](https://github.com/thymeleaf/thymeleaf.github.com/blob/master/doc/tutorials/2.1/usingthymeleaf.html) has a link: "http://www.thymeleaf.org/doc/fromhtmltohtmlviahtml.html" which 404s. I tried to google the article but couldn't find a working link to replace it with.

**Comment by ultraq** [comment]
Link updated and docs regenerated w/ the fixed link.  Thanks for the bug report!

**Comment by ultraq** [comment]
Oh yeah, the link was supposed to point to another article in our docs pages: http://www.thymeleaf.org/doc/articles/fromhtmltohtmlviahtml.html
