### ISSUE TITLE
www.thymeleaf.org should be HTTPS

### ISSUE THREAD

**Issue by candrews** [thymeleaf/thymeleaf.github.com#28]
The thymeleaf site, www.thymeleaf.org, should be available over HTTPS.

A certificate could be freely acquired from https://letsencrypt.org/ so this should be a 0 dollar, purely effort/infrastructure task.

**Comment by danielfernandez** [comment]
The Thymeleaf website is hosted on GitHub itself (GitHub Pages) and, unfortunately, as of today GitHub only implements HTTPS support for `*.github.io` subdomains, not for custom domains.

I'm closing this in favour of #29, so that we don't leave duplicate issues.

**Comment by danielfernandez** [comment]
GitHub has finally enabled HTTPS for custom domains, and thymeleaf.org now forces HTTPS.
