### ISSUE TITLE
Certificate Error (CN field invalid)

### ISSUE THREAD

**Issue by karlind** [thymeleaf/thymeleaf.github.com#29]
Official website has error on https configuration.

The `CN` field of certificate is invalid. It should be `www.thymeleaf.org` rather than `www.github.com`.

Every time I open `https://www.thymeleaf.org`, I got an alert:
```
Certificate Error
There are issues with the site's certificate chain (net::ERR_CERT_COMMON_NAME_INVALID).
```

**Comment by danielfernandez** [comment]
The Thymeleaf website is hosted on GitHub itself (GitHub Pages) and, unfortunately, as of today GitHub only implements HTTPS support for `*.github.io` subdomains, not for custom domains.

I'm leaving this open for the future, so that it can be re-evaluated once GitHub adds such support.

**Comment by danielfernandez** [comment]
GitHub has finally enabled HTTPS for custom domains, and thymeleaf.org now forces HTTPS.
