### ISSUE TITLE
[16 Template Cache] A mistake in the description of the template cache default setting.

### ISSUE THREAD

**Issue by yoshikawaa** [thymeleaf/thymeleaf.github.com#30]
#### Version
3.0.8.RELEASE 

#### Problem
At [Using Thymeleaf/16 Template Cache](http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#template-cache), default value of template cache max size is `50`.
But at [StandardCacheManager.java#L87](https://github.com/thymeleaf/thymeleaf/blob/thymeleaf-3.0.8.RELEASE/src/main/java/org/thymeleaf/cache/StandardCacheManager.java#L87), actual default value is `200`.

As it relates to memory tuning, I think it's better to fix it.

Please consider, thanks.

**Comment by danielfernandez** [comment]
Fixed, thanks!
