### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by NaumanMoazzam** [thymeleaf/thymeleaf.github.com#34]
Write a Readme file so one can know about what this repo is about. 
Thanks.

**Comment by ultraq** [comment]
Thanks for the suggestion, but I'm going to close this one as I feel we have some information in places that lets people know what it's about:
 - the repository has a description of "Thymeleaf website" with the URL that it lives at
 - the repository is named following the GitHub convention of (project).github.com which identifies it as a website project

We could add a readme but it would only repeat the information above.  Maybe at a later stage if we want to encourage contributions to the website?  We'd rather encourage contributions to the Thymeleaf project/subprojects instead.
