### ISSUE TITLE
Your website can not open in china

### ISSUE THREAD

**Issue by Hgqin** [thymeleaf/thymeleaf.github.com#37]
Is fiexed?

**Comment by ultraq** [comment]
I tried a few sites that can check website access from China, and they've all come back OK.  Hopefully what you experienced is temporary?

**Comment by Hgqin** [comment]
> I tried a few sites that can check website access from China, and they've all come back OK. Hopefully what you experienced is temporary?

Thank you. My problem, but China Unicom's default DNS does not seem to have you. I can access it after changing DNS.
