### ISSUE TITLE
www.thymeleaf.org down?

### ISSUE THREAD

**Issue by fabcep** [thymeleaf/thymeleaf.github.com#38]
Hi Thymeleaf team,

The website https://www.thymeleaf.org/ is down. Is that on purpose? 

I thought a drop you a note letting you know.

Regards,

Fabio

**Comment by ultraq** [comment]
Website should be back up again 🙂

**Comment by danielfernandez** [comment]
Thanks. We renamed the default branch in the site's repository and it seems GitHub Pages automatic recognition of this wasn't as fast as we thought it would be :)
