### ISSUE TITLE
Thymeleaf documentation - not found github

### ISSUE THREAD

**Issue by cjcalmeida** [thymeleaf/thymeleaf.github.com#39]
When you try to open thymeleaf site (https://thymeleaf.org), status code not found (404) is returned.

**Comment by ultraq** [comment]
Website should be back up again 🙂

**Comment by danielfernandez** [comment]
Thanks. We renamed the default branch in the site's repository and it seems GitHub Pages automatic recognition of this wasn't as fast as we thought it would be :)
