### ISSUE TITLE
SVG version of Thymeleaf logo?

### ISSUE THREAD

**Issue by Potherca** [thymeleaf/thymeleaf.github.com#41]
Is there an SVG version of the Thymeleaf logo available?

The reason for asking is that we would like to add the Thymeleaf logo to the PlantUML std-lib (through one of the sub-repos at https://github.com/plantuml-stdlib/).

The easiest way to do so would be using an SVG but I can't seem to find an official one.

The [link in the "Downloads" page](https://github.com/thymeleaf/thymeleaf.github.com/blob/main/download.html#L255) points to https://github.com/thymeleaf/thymeleaf-dist/tree/main/src/artwork/thymeleaf%202016 but that no longer seems to exist.

**Comment by mahozad** [comment]
@danielfernandez 
I can probably convert the PNG logo to SVG.

Would you like me to do that?

**Comment by Potherca** [comment]
> I can probably convert the PNG logo to SVG.

@mahozad If it is not too much hassle, that would be greatly appreciated!

**Comment by danielfernandez** [comment]
Please see https://github.com/thymeleaf/thymeleaf-org/tree/main/artwork/thymeleaf%202016

**Comment by Potherca** [comment]
@danielfernandez Supercool! Thanks!
