### ISSUE TITLE
Code examples in documentation are hardly readable for printed version

### ISSUE THREAD

**Issue by dmorellet** [thymeleaf/thymeleaf.github.com#9]
The black background in the code snippets, when printed, make it hard to read, and we can't add notes or underline/highlight anything, contrarly to a previous version...

**Comment by ultraq** [comment]
The website redesign for Thymeleaf 3 changed the styles, although the code colours did stay largely the same.  I don't have access to a printer right now, so I should check the updated designs and their legibility when printed when I'm somewhere with a printer.

**Comment by ultraq** [comment]
Print preview of our docs and tutorials for code samples looks much more legible:

![screen shot 2017-04-21 at 11 47 57 pm](https://cloud.githubusercontent.com/assets/1686920/25276195/0ca07df6-26ed-11e7-89af-133926e927e2.png)

![screen shot 2017-04-21 at 11 48 08 pm](https://cloud.githubusercontent.com/assets/1686920/25276197/0eb6091c-26ed-11e7-8cd7-6febb487211c.png)

Probably a few other doc things that could make it better, but those might affect the PDF version of our docs as they use the print stylesheet for their styles as well.  Closing.
